"""
Pet database with 15 pets and their lifestyle compatibility scores.

Each pet has attributes scored 1-5:
  - space_need: 1 = tiny space ok, 5 = needs large yard
  - time_need: 1 = very low maintenance, 5 = needs constant attention
  - activity_level: 1 = sedentary, 5 = very active
  - noise_level: 1 = silent, 5 = very noisy
  - cost: 1 = very affordable, 5 = expensive
  - kid_friendly: 1 = not recommended, 5 = excellent with kids

Climate preference: "hot", "cold", "moderate", "any"
"""

PETS = [
    {
        "id": "golden_retriever",
        "name": "Golden Retriever",
        "type": "Dog",
        "image": "1776401886278-123059017.webp",
        "description": "Friendly, intelligent, and devoted. Golden Retrievers are one of the most popular family dogs, known for their gentle temperament and love of play.",
        "space_need": 4,
        "time_need": 4,
        "activity_level": 4,
        "noise_level": 3,
        "cost": 4,
        "kid_friendly": 5,
        "climate": ["moderate", "cold"],
        "lifespan": "10-12 years",
        "traits": ["friendly", "loyal", "active", "intelligent", "gentle", "family"],
    },
    {
        "id": "labrador",
        "name": "Labrador Retriever",
        "type": "Dog",
        "image": "1776401886313-621002830.webp",
        "description": "Outgoing, active, and fun-loving. Labs are versatile dogs that excel as family companions, service dogs, and sporting partners.",
        "space_need": 4,
        "time_need": 4,
        "activity_level": 5,
        "noise_level": 3,
        "cost": 4,
        "kid_friendly": 5,
        "climate": ["moderate", "cold"],
        "lifespan": "10-14 years",
        "traits": ["energetic", "loyal", "friendly", "athletic", "playful", "family"],
    },
    {
        "id": "corgi",
        "name": "Welsh Corgi",
        "type": "Dog",
        "image": "1776402012265-455387826.webp",
        "description": "Bold, affectionate, and surprisingly athletic for their size. Corgis are compact herding dogs with big personalities and adorable stubby legs.",
        "space_need": 3,
        "time_need": 3,
        "activity_level": 4,
        "noise_level": 4,
        "cost": 3,
        "kid_friendly": 4,
        "climate": ["moderate", "cold"],
        "lifespan": "12-15 years",
        "traits": ["playful", "alert", "compact", "smart", "loyal", "energetic"],
    },
    {
        "id": "beagle",
        "name": "Beagle",
        "type": "Dog",
        "image": "beagle.webp",
        "description": "Curious, merry, and friendly. Beagles are scent hounds with an excellent nose and a cheerful disposition that makes them great companions.",
        "space_need": 3,
        "time_need": 3,
        "activity_level": 4,
        "noise_level": 4,
        "cost": 3,
        "kid_friendly": 5,
        "climate": ["any"],
        "lifespan": "12-15 years",
        "traits": ["curious", "friendly", "merry", "compact", "vocal", "family"],
    },
    {
        "id": "pomeranian",
        "name": "Pomeranian",
        "type": "Dog",
        "image": "pomeranian.webp",
        "description": "Lively, bold, and inquisitive. Pomeranians pack a big personality into a tiny body, making them perfect apartment companions.",
        "space_need": 1,
        "time_need": 3,
        "activity_level": 3,
        "noise_level": 4,
        "cost": 3,
        "kid_friendly": 2,
        "climate": ["moderate", "cold"],
        "lifespan": "12-16 years",
        "traits": ["small", "fluffy", "alert", "bold", "apartment", "companion"],
    },
    {
        "id": "persian_cat",
        "name": "Persian Cat",
        "type": "Cat",
        "image": "persian_cat.webp",
        "description": "Calm, gentle, and elegant. Persian cats are the epitome of relaxation, preferring quiet environments and gentle affection.",
        "space_need": 1,
        "time_need": 3,
        "activity_level": 1,
        "noise_level": 1,
        "cost": 4,
        "kid_friendly": 3,
        "climate": ["moderate", "cold"],
        "lifespan": "12-17 years",
        "traits": ["calm", "quiet", "fluffy", "elegant", "indoor", "gentle"],
    },
    {
        "id": "siamese_cat",
        "name": "Siamese Cat",
        "type": "Cat",
        "image": "siamese_cat.webp",
        "description": "Social, vocal, and intelligent. Siamese cats are known for their striking blue eyes, sleek coat, and love of conversation with their humans.",
        "space_need": 2,
        "time_need": 3,
        "activity_level": 3,
        "noise_level": 4,
        "cost": 3,
        "kid_friendly": 4,
        "climate": ["moderate", "hot"],
        "lifespan": "15-20 years",
        "traits": ["social", "vocal", "intelligent", "sleek", "affectionate", "playful"],
    },
    {
        "id": "hamster",
        "name": "Syrian Hamster",
        "type": "Small Animal",
        "image": "hamster.webp",
        "description": "Adorable, low-maintenance, and fun to watch. Hamsters are perfect starter pets that don't require much space or time commitment.",
        "space_need": 1,
        "time_need": 1,
        "activity_level": 2,
        "noise_level": 1,
        "cost": 1,
        "kid_friendly": 3,
        "climate": ["moderate"],
        "lifespan": "2-3 years",
        "traits": ["tiny", "low-maintenance", "nocturnal", "affordable", "apartment", "starter"],
    },
    {
        "id": "guinea_pig",
        "name": "Guinea Pig",
        "type": "Small Animal",
        "image": "guinea_pig.webp",
        "description": "Social, gentle, and vocal. Guinea pigs are wonderful small pets that love interaction and rarely bite, making them ideal for families.",
        "space_need": 1,
        "time_need": 2,
        "activity_level": 2,
        "noise_level": 2,
        "cost": 2,
        "kid_friendly": 5,
        "climate": ["moderate"],
        "lifespan": "5-7 years",
        "traits": ["gentle", "social", "vocal", "family", "apartment", "affordable"],
    },
    {
        "id": "rabbit",
        "name": "Holland Lop Rabbit",
        "type": "Small Animal",
        "image": "rabbit.webp",
        "description": "Affectionate, playful, and surprisingly intelligent. Rabbits can be litter-trained and form deep bonds with their owners.",
        "space_need": 2,
        "time_need": 3,
        "activity_level": 3,
        "noise_level": 1,
        "cost": 2,
        "kid_friendly": 4,
        "climate": ["moderate", "cold"],
        "lifespan": "7-12 years",
        "traits": ["quiet", "affectionate", "intelligent", "playful", "litter-trained", "soft"],
    },
    {
        "id": "parrot",
        "name": "Budgerigar (Budgie)",
        "type": "Bird",
        "image": "parrot.webp",
        "description": "Cheerful, social, and capable of learning speech. Budgies are colorful little parrots that bring joy and entertainment to any home.",
        "space_need": 1,
        "time_need": 3,
        "activity_level": 3,
        "noise_level": 3,
        "cost": 2,
        "kid_friendly": 3,
        "climate": ["moderate", "hot"],
        "lifespan": "5-10 years",
        "traits": ["colorful", "social", "talkative", "apartment", "entertaining", "smart"],
    },
    {
        "id": "goldfish",
        "name": "Fancy Goldfish",
        "type": "Fish",
        "image": "goldfish.webp",
        "description": "Beautiful, calming, and extremely low-maintenance. Goldfish are classic pets that add elegance and tranquility to any space.",
        "space_need": 1,
        "time_need": 1,
        "activity_level": 1,
        "noise_level": 1,
        "cost": 1,
        "kid_friendly": 3,
        "climate": ["any"],
        "lifespan": "10-15 years",
        "traits": ["quiet", "calming", "low-maintenance", "affordable", "apartment", "beautiful"],
    },
    {
        "id": "betta_fish",
        "name": "Betta Fish",
        "type": "Fish",
        "image": "betta_fish.webp",
        "description": "Vibrant, graceful, and easy to care for. Betta fish are stunning with their flowing fins and brilliant colors, perfect for small spaces.",
        "space_need": 1,
        "time_need": 1,
        "activity_level": 1,
        "noise_level": 1,
        "cost": 1,
        "kid_friendly": 3,
        "climate": ["moderate", "hot"],
        "lifespan": "3-5 years",
        "traits": ["beautiful", "colorful", "low-maintenance", "affordable", "apartment", "solo"],
    },
    {
        "id": "leopard_gecko",
        "name": "Leopard Gecko",
        "type": "Reptile",
        "image": "leopard_gecko.webp",
        "description": "Docile, fascinating, and easy to handle. Leopard geckos are beginner-friendly reptiles with charming spotted patterns and gentle personalities.",
        "space_need": 1,
        "time_need": 1,
        "activity_level": 1,
        "noise_level": 1,
        "cost": 2,
        "kid_friendly": 3,
        "climate": ["hot", "moderate"],
        "lifespan": "15-20 years",
        "traits": ["docile", "quiet", "low-maintenance", "fascinating", "apartment", "unique"],
    },
    {
        "id": "turtle",
        "name": "Red-Eared Slider Turtle",
        "type": "Reptile",
        "image": "turtle.webp",
        "description": "Calm, long-lived, and endlessly interesting. Turtles are unique pets that offer a relaxing and rewarding pet-keeping experience.",
        "space_need": 2,
        "time_need": 2,
        "activity_level": 1,
        "noise_level": 1,
        "cost": 3,
        "kid_friendly": 3,
        "climate": ["moderate", "hot"],
        "lifespan": "20-40 years",
        "traits": ["calm", "long-lived", "unique", "quiet", "fascinating", "resilient"],
    },
]


def get_all_pets():
    """Return a list of all pets (safe copy)."""
    return [pet.copy() for pet in PETS]


def get_pet_by_id(pet_id):
    """Return a single pet by its ID."""
    for pet in PETS:
        if pet["id"] == pet_id:
            return pet.copy()
    return None